
name: release

on: push

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./configure.py --cc=clang --disable-shared-library --prefix install
          make -j8
          make install
      - name: archive artifacts on sha
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.sha }}
          path: install
      - name: archive artifacts on tag
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.ref }}
          path: install

  windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: |
          python3 configure.py --cc=msvc --disable-shared-library --os=windows --prefix install
          nmake
          nmake check
          nmake install
      - name: archive artifacts on sha
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ github.sha }}
          path: install
      - name: archive artifacts on tag
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ github.ref }}
          path: install
